Repository GDGoCINHA/24-2_GDGoC_Web, pull requests merged in 2025-03, with the labels that each got.

#36 Feat, Refactor(#16)/landing page 리팩토링, 스터디 페이지 추가
  public/src/images/study/figma.png
  public/src/images/study/github.png
  public/src/images/study/notion.png
  public/src/images/study/study1.jpg
  public/src/images/study/study2.jpg
  public/src/images/study/study3.jpg
  public/src/images/study/study4.jpg
  public/src/images/study/study5.jpg
  src/app/page.jsx
  src/components/Header.jsx
  src/components/sections/AboutSection.jsx
  src/components/sections/ActivitiesSection.jsx
  src/components/sections/CTASection.jsx
  src/components/sections/HeroSection.jsx
  src/components/sections/PartnersSection.jsx
  src/components/sections/StatsSection.jsx
  src/components/sections/StudySection.jsx
Labels: FEAT, REFACTOR

#37 Fix(#16)/Landing 페이지 heroSection 버튼 마진 제거
  src/components/sections/HeroSection.jsx
Labels: FIX, 🛠️ DEVELOP

#38 Feat, Refactor, Fix(#16)/ 랜딩 페이지 리펙토링, 스터디 섹션 추가 및 버튼 마진 수정
  public/src/images/study/figma.png
  public/src/images/study/github.png
  public/src/images/study/notion.png
  public/src/images/study/study1.jpg
  public/src/images/study/study2.jpg
  public/src/images/study/study3.jpg
  public/src/images/study/study4.jpg
  public/src/images/study/study5.jpg
  src/app/page.jsx
  src/components/Header.jsx
  src/components/sections/AboutSection.jsx
  src/components/sections/ActivitiesSection.jsx
  src/components/sections/CTASection.jsx
  src/components/sections/HeroSection.jsx
  src/components/sections/PartnersSection.jsx
  src/components/sections/StatsSection.jsx
  src/components/sections/StudySection.jsx
Labels: FIX, FEAT, REFACTOR, 💻 MASTER

#41 Feat / 배포 cicd 구축
  .github/workflows/deploy.yml
  Dockerfile
  appspec.yml
  scripts/deploy.sh
Labels: FEAT, 💻 MASTER

#42 Fix: codedeploy trigger 플러그인에서 aws cli 로 변경
  .github/workflows/deploy.yml
Labels: FIX, 💻 MASTER

#73 Chore(#8)/ recruit submit 이름 변경 및 가입 완료문구 변경
  src/app/recruit/page.jsx
  src/app/recruit/submit/page.jsx
Labels: 💻 MASTER
