Repository GDGoCINHA/24-2_GDGoC_Web, pull requests merged in 2025-08, with the labels that each got.

#147 Fix(#4)/ 비밀번호 재설정 과정 이메일 전달 로직 및 UI 수정 #4
  src/app/auth/signin/page.jsx
  src/components/auth/screen/AuthResetPassword.jsx
  src/components/auth/screen/AuthResetRequest.jsx
Labels: FIX, TODO, 🛠️ DEVELOP

#148 Deploy(#102)/ Main페이지, Recruit 페이지 업데이트 및 로그인 비밀번호 재설정 로직 수정 반영
  package-lock.json
  public/icons/logo/chatgpt.png
  public/icons/logo/django.png
  public/icons/logo/figma.png
  public/icons/logo/python.png
  public/images/activity/buildwithai.png
  public/images/activity/seminar_bg.png
  src/app/auth/signin/page.jsx
  src/app/main/page.jsx
  src/app/recruit/page.jsx
  src/components/auth/screen/AuthResetPassword.jsx
  src/components/auth/screen/AuthResetRequest.jsx
  src/components/main/CardCarousel.jsx
  src/components/main/EventCard.jsx
  src/components/main/FAQ.jsx
  src/components/main/MainCarousel.jsx
  src/components/recruit/screen/Recruit7.jsx
  src/components/recruit/screen/Recruit8.jsx
  src/components/study/dashboard/admin/detail/ReviewApplication.jsx
  src/components/ui/common/MenuHeader.jsx
  src/constant/semesterOptions.js
  src/mock/events.js
  yarn.lock
Labels: FIX, FEAT, 💻 MASTER

#149 Fix/render
  next.config.ts
  src/app/_auth/signin/[social]/callback/page.jsx
  src/app/_auth/signin/layout.js
  src/app/_auth/signin/page.jsx
  src/app/_auth/signup/layout.js
  src/app/_auth/signup/page.jsx
  src/app/_study/(dashboard)/admin/[id]/page.jsx
  src/app/_study/(dashboard)/admin/page.jsx
  src/app/_study/(dashboard)/my/[id]/page.jsx
  src/app/_study/(dashboard)/my/page.jsx
  src/app/_study/apply/[id]/page.jsx
  src/app/_study/create/page.jsx
  src/app/_study/detail/[id]/page.jsx
  src/app/_study/layout.js
  src/app/_study/loading.js
  src/app/_study/page.jsx
  src/app/admin/layout.js
  src/app/admin/page.jsx
  src/app/main/layout.js
  src/app/robots.js
  src/app/sitemap.js
  src/app/test/page.jsx
  src/components/auth/ApiCodeGuard.jsx
  src/hooks/useAuthApi.js
  src/middleware.ts
  src/services/auth/signin/custom/CustomAuthApi.js
  yarn.lock
Labels: REFACTOR
