Repository GDGoCINHA/24-2_GDGoC_Web, pull requests merged in 2025-05, with the labels that each got.

#97 Fix(#4, #75)/ router proxy 설정 및 study useEffect 수정
  src/app/api/auth/[route]/route.js
  src/hooks/study/useApplicantDetail.js
  src/hooks/study/useApplicantList.js
  src/hooks/study/useAppliedStudyList.js
  src/hooks/study/useCreatedStudyList.js
  src/hooks/study/useStudyAccessCheck.js
  src/hooks/study/useStudyDetail.js
  src/hooks/study/useStudyList.js
  src/hooks/useAuthApi.js
Labels: FIX, 🛠️ DEVELOP

#100 Fix(#4) 프록시 대상 주소 변경
  src/app/api/auth/[route]/route.js
Labels: FIX, 🛠️ DEVELOP

#101 Fix(#4) 프록시 대상 주소 변경
  src/app/api/auth/[route]/route.js
Labels: FIX, 💻 MASTER

#103 Update: 스터디 API 테스트를 위해 수정된 프록시 관련 파일 받기
  src/app/api/auth/[route]/route.js
  src/hooks/useAuthApi.js
Labels: Update

#104 Fix(#4)/ 프록시 대상 주소 재변경
  src/app/api/[route]/route.js
Labels: FIX, 🛠️ DEVELOP

#105 Fix(#4)/ 프록시 대상 주소 재변경
  src/app/api/[route]/route.js
  src/components/study/dashboard/admin/view/CreatedStudies.jsx
  src/components/study/dashboard/my/view/AppliedStudies.jsx
  src/components/study/ui/card/ApplicantInfoList.jsx
  src/hooks/study/useApplicantDetail.js
  src/hooks/study/useApplicantList.js
  src/hooks/study/useAppliedStudyList.js
  src/hooks/study/useCreatedStudyList.js
  src/hooks/study/useStudyAccessCheck.js
  src/hooks/study/useStudyDetail.js
  src/hooks/study/useStudyList.js
Labels: FIX, FEAT, 💻 MASTER

#108 Fix(#4)/ 인증 토큰 API 엔드포인트 변경
  src/app/api/auth/refresh/route.js
Labels: 🛠️ DEVELOP, HotFix

#109 Fix(#4)/ 인증 토큰 API 엔드포인트 변경
  src/app/api/auth/refresh/route.js
Labels: 💻 MASTER, HotFix

#111 Fix(#4)/ 인증 토큰 처리 및 API 요청 설정 수정
  src/hooks/useAuthApi.js
  src/hooks/useAuthenticatedApi.js
  yarn.lock
Labels: FIX, 🛠️ DEVELOP

#110 Feat(#106)/ meta 파일 생성 및 수정
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/manifest.json
  public/next.svg
  public/screenshots/home.png
  public/vercel.svg
  src/app/layout.js
  src/app/robots.js
  src/app/sitemap.js
Labels: FEAT, COMPLETE, 🛠️ DEVELOP

#112 Deploy(#102)/Fix(#4)/Feat(#106)/ SEO 최적화 및 인증 관련 기능 개선 반영
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/manifest.json
  public/next.svg
  public/screenshots/home.png
  public/vercel.svg
  src/app/layout.js
  src/app/robots.js
  src/app/sitemap.js
  src/hooks/useAuthApi.js
  src/hooks/useAuthenticatedApi.js
  yarn.lock
Labels: FIX, FEAT, 💻 MASTER

#113 Update: 스터디 API 인터셉트를 위한 파일 가져오기
  .github/workflows/deploy.yml
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/manifest.json
  public/next.svg
  public/screenshots/home.png
  public/vercel.svg
  src/app/api/auth/refresh/route.js
  src/app/auth/signin/page.jsx
  src/app/layout.js
  src/app/robots.js
  src/app/sitemap.js
  src/hooks/study/useStudyDetail.js
  src/hooks/useAuthApi.js
  src/hooks/useAuthenticatedApi.js
  yarn.lock
Labels: Update

#114 Fix(#102): to apply .env to right directory
  .github/workflows/deploy.yml
  Dockerfile
Labels: FIX, 💻 MASTER

#115 HotFix(#102): to apply .env to right directory
  .github/workflows/deploy.yml
Labels: 💻 MASTER, HotFix

#118 Fix(#96)/ 스터디 API 연결 업데이트
  src/app/study/(dashboard)/admin/[id]/page.jsx
  src/app/study/(dashboard)/admin/page.jsx
  src/app/study/(dashboard)/my/[id]/page.jsx
  src/app/study/(dashboard)/my/page.jsx
  src/app/study/apply/[id]/page.jsx
  src/app/study/create/page.jsx
  src/app/study/detail/[id]/page.jsx
  src/app/study/layout.js
  src/app/study/loading.js
  src/app/study/page.jsx
  src/components/MarginBottom.jsx
  src/components/study/StudyHeader.jsx
  src/components/study/StudySection.jsx
  src/components/study/dashboard/InfoArea.jsx
  src/components/study/dashboard/admin/detail/DetailArea.jsx
  src/components/study/dashboard/admin/detail/ReviewApplication.jsx
  src/components/study/dashboard/admin/view/CreatedStudies.jsx
  src/components/study/dashboard/my/detail/DetailArea.jsx
  src/components/study/dashboard/my/detail/StudyDetail.jsx
  src/components/study/dashboard/my/view/AppliedStudies.jsx
  src/components/study/dashboard/my/view/ViewArea.jsx
  src/components/study/ui/card/ApplicantInfoList.jsx
  src/components/study/ui/card/NoticeBanner.jsx
  src/components/study/ui/card/StudyCard.jsx
  src/components/study/ui/modal/ApplicantDetailModal.jsx
  src/components/study/ui/nav/StudyDashboardNav.jsx
  src/components/study/ui/nav/StudyTypeNav.jsx
  src/components/ui/button/GreenTextButton.jsx
  src/components/ui/button/RoundImageButton.jsx
  src/components/ui/button/SubmitButton.jsx
  src/services/study/useApplicantDetail.js
  src/services/study/useApplicantList.js
  src/services/study/useAppliedStudyList.js
  src/services/study/useCreatedStudyList.js
  src/services/study/useStudyAccessCheck.js
  src/services/study/useStudyDetail.js
  src/services/study/useStudyList.js
Labels: FIX, COMPLETE, REFACTOR, 🛠️ DEVELOP

#120 HotFix: 일부 스터디 API 기능 문제 해결
  src/app/study/create/page.jsx
  src/components/study/dashboard/admin/detail/ReviewApplication.jsx
Labels: 💻 MASTER, HotFix

#121 HotFix: 이미지 업로드 API 오타 수정
  src/app/layout.js
  src/app/study/create/page.jsx
Labels: 💻 MASTER, HotFix

#122 HotFix: fix fetching JSON data of API
  src/app/study/create/page.jsx
Labels: 💻 MASTER, HotFix

#126 Fix: CI/CD 스크립트 개선 및 Google 로그인 credentials 수정 사항 배포
  .github/workflows/note.md
  src/app/auth/signin/google/GoogleAuthApi.js
  src/hooks/useAuthApi.js
  yarn.lock
Labels: FIX, 💻 MASTER

#127 Fix: 프로덕션 환경에 따른 쿠키 도메인 설정 추가 #4
  src/app/api/auth/refresh/route.js
  src/app/api/signin/route.js
Labels: FIX, 💻 MASTER

#130 Fix: 입금 계좌 정보 변경
  src/app/recruit/screen/Recruit11.jsx
Labels: FIX

#131 Fix: 입금 게좌 수정/ api 경로 개선
  .github/workflows/deploy.yml
  src/app/api/auth/refresh/route.js
  src/app/api/signin/route.js
  src/app/auth/signin/custom/CustomAuthApi.js
  src/app/auth/signin/google/GoogleAuthApi.js
  src/app/auth/signin/screen/AuthFindId.jsx
  src/app/auth/signin/screen/AuthResetPassword.jsx
  src/app/auth/signin/screen/AuthResetRequest.jsx
  src/app/main/Header.jsx
  src/app/main/components/CardCarousel.jsx
  src/app/main/components/EventCard.jsx
  src/app/main/components/MainCarousel.jsx
  src/app/main/page.jsx
  src/app/recruit/page.jsx
  src/app/recruit/screen/Recruit11.jsx
  src/hooks/useAuthApi.js
  src/hooks/useAuthenticatedApi.js
Labels: FIX, 💻 MASTER

#132 Update(#129)/ CI/CD env 변수 추가
  .github/workflows/deploy.yml
Labels: 💻 MASTER, HotFix

#138 Feat/ API 라우터 수정 및 미들웨어 일시적 추가
  .github/ISSUE_TEMPLATE/문제-수정-요청.md
  .github/ISSUE_TEMPLATE/신규-기능-개발.md
  .github/workflows/deploy.yml
  .github/workflows/note.md
  src/app/api/auth/refresh/route.js
  src/app/api/auth/refresh/route.ts
  src/app/api/auth/signin/route.js
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signout/route.ts
  src/hooks/useAuthApi.js
  src/lib/rate-limit.ts
  src/middleware.ts
Labels: FEAT, 💻 MASTER

#139 HotFix: only check for refresh token
  src/middleware.ts
Labels: 💻 MASTER, HotFix

#143 Update,Fix(#4,#102)/ 회원가입 페이지로 리디렉션 수정 및 프로젝트 링크 페이지 추가
  package.json
  src/components/auth/screen/AuthLogin.jsx
  src/components/ui/common/MenuHeader.jsx
  src/services/auth/signin/google/GoogleAuth.js
  yarn.lock
Labels: FIX, 💻 MASTER, Update
