Repository GDGoCINHA/24-2_GDGoC_Web, pull requests merged in 2025-02, with the labels that each got.

#32 Refactor(#8)/ Recruit 컴포넌트 랜더링 최적화
  src/app/recruit/page.jsx
Labels: REFACTOR

#33 Feat, Refector(#8)/가입페이지 문구 수정 및 리팩토링
  src/app/recruit/page.jsx
  src/app/recruit/submitted/page.jsx
  yarn.lock
Labels: FEAT, REFACTOR

#34 Feat(#8)/Recruit 학번, 전화번호 중복확인 버튼 구현
  src/app/recruit/screen/Recruit2.jsx
  src/app/recruit/screen/Recruit3.jsx
Labels: FEAT, COMPLETE, 🛠️ DEVELOP

#35 Feat(#8)/ Recruit 학번, 전화번호 중복확인 버튼 구현
  src/app/recruit/screen/Recruit2.jsx
  src/app/recruit/screen/Recruit3.jsx
Labels: FEAT, 💻 MASTER
